### ISSUE TITLE
[BUG] Updating Database Errors

### ISSUE THREAD

**Issue by stratoru** [Deamon87/WebWowViewerCpp#19]
Having an issue updating the database the last month or so. I get the following errors consistently:
 
![image](https://user-images.githubusercontent.com/43893231/206880302-82926208-d998-4a4c-84cc-32da1c1f66d4.png)

![image](https://user-images.githubusercontent.com/43893231/206880305-9e96ba38-81e0-40b4-a5f3-5d22b47c1c51.png)

Here is the export.db3 file it's creating, which is empty: 

![image](https://user-images.githubusercontent.com/43893231/206880321-d92c9234-062f-4550-b978-08faa11e6b5b.png)

The definitions files seem to be updating appropriately, so not sure why the error is occurring between here and creating the actual export.db3:

![image](https://user-images.githubusercontent.com/43893231/206880344-bcca4072-b7f9-4219-ada8-62beaf006a9d.png)

This is using the latest version (1.0), on Windows 10.  Love this tool and hope to be able to keep using it now that wow.tools map viewer is defunct.

**Comment by Deamon87** [comment]
Should be fixed in 0.1.1 version. I was an issue of changed format and CascLib dependency had to be updated to the latest version

**Comment by Deamon87** [comment]
Release is ready

**Comment by stratoru** [comment]
Working great again, thank you so much! And thanks for making this tool, it is absolutely fantastic.

**Comment by Deamon87** [comment]
Yeah. I will add "disable portal culling" into UI in next release. The support for it is already implemented in the code, It's just it's not in the UI yet.
